### ISSUE TITLE
External script doesn't work anymore

### ISSUE THREAD

**Issue by chros73** [nicko88/HTPCRemote#2]
I created a simple batch file that I used couple of times, until I wanted add a new button. Since then, my orignal button doesn't work.
Content of batch file:
```sh
aiopylgtvcommand 192.168.1.78 info_button
```

See attached zip for config. [HTPCRemote.zip](https://github.com/nicko88/HTPCRemote/files/5271621/HTPCRemote.zip)
And thanks for the colored background! :)

**Comment by chros73** [comment]
I just tried out one more time and it works :) Dunno what happened.
Thanks!

**Comment by nicko88** [comment]
It's all good.

Yeah, I didn't change anything related to that, but I guess if you can find a pattern to why it might not work sometimes in the future, I could adjust something, but I don't know what I would adjust at this time.

It pretty much just runs the script rather simply.

**Comment by chros73** [comment]
Thanks for the reply. Maybe I wasn't clear, I was still using the old 1.1.1 version when it happened. I just upgraded now to the recent one, so it's not caused by the new version :)

**Comment by nicko88** [comment]
Ah I see.

Yeah if there is a better way for me to be running scripts than this:  
https://github.com/nicko88/HTPCRemote/blob/master/HTPCRemote/Devices/Controllers/WinControl.cs#L17

I do not know, but let me know if you ever run into any more troubles.

**Comment by chros73** [comment]
Cheers.
- I noticed that in Task Scheduler there are lot of instances of "cmd" and aiopylgtvcommand are still running, so they don't exit. :(
- is the "Param" works for you when targeting an application? It doesn't for me.
```json
    {
      "ItemType": 2,
      "Label": ">||",
      "RelativeSize": 1,
      "Color": "Green",
      "Commands": [
        {
          "DeviceName": "keys",
          "Cmd": "{SPACE}",
          "Param": "mpc-hc64"
        }
      ]
    },
```

And can be this modified to target multiple apps? e.g. "mpc*" or [mpc-|hc64|be64] or something?
I use both mpc-hc and be and would be nice if 1 remote would work for both of them (including the x86 versions as well).

**Comment by nicko88** [comment]
Does it exit when you run the .bat manually?

HTPCRemote just runs the .bat so I don't know why it wouldn't exit, or why it would behave any differently than when you double click on it manually.  I have not seen that happen with any of the .bat files I have been triggering.

The param for the "keys" remote is supposed to bring the named application to the foreground and set it to the active window, so that it receives the keys.  It works when I test it.

The code that does this is this, where "app" is the param string.

```
Process process = Process.GetProcessesByName(app).FirstOrDefault();
ShowWindow(process.MainWindowHandle, 1);
SetForegroundWindow(process.MainWindowHandle);
```

I could make a change to support matching multiple but I am not sure it's really needed.  If I did this would it be enough to just treat the param as a "contains"?  Like find the application running that contains "mpc-" without specifying where the wildcards are?

Otherwise what you could always do now and what I would suggest if you are using multiple mpc players is to use the mpc device control.

If you only ever have 1 of them running at a time, then set the remote control port the same on all of them and your button will control whichever one is running since all mpc players use the exact same IP control commands.

If you want to be able to run multiple at once and control them all, I don't see why you couldn't just set each different mpc player to a different remote port number and in your mpc buttons just put multiple commands.  Send the same command to each mpc/port that you defined in the devices configuration and the button will send your command to any active mpc players, if that make sense.

**Comment by chros73** [comment]
> I will do some research some time though to see if sending keys to background windows is possible

OK, thanks, it's better than nothing now. :)

Maybe [these](https://stackoverflow.com/questions/12805345/send-combination-of-keystrokes-to-background-window) help. (I implemented the accepted answer in my JS remote, but - although it worked - it was so slow that I removed it, so it can also only send keys to foreground apps.) Maybe the 2nd answer?

> I would suggest what I mentioned above about using the mpc IP control

Yes, that's what the Remoti.co Android app uses with MPC-HC/BE. But I want to send keystrokes to madvr :)

> I could make a change to support matching multiple. I could pretty easily just do at least "name*" (starts with), "*name" (ends with), and "*name*" (contains) so I will do that later tonight.

Here's the use case: multiple monitors, only 1 mpc-* instance is used at a time. mpc-hc is set up to decode all audio formats, mpc-be is set-up to do audio bitstreaming.
So, yes, "*name*" (contains) can be good, but you have to be aware to select always the 1st process (it can return more).
Or, what about this? Comma separated list in Param:
`"Param": "mpc-hc64,mpc-be64,mpc-hc,mpc-be"`
You loop through these values and always send a key to the first you found.

> Does it exit when you run the .bat manually?

Yes, of course :) Here's the command one more time: `aiopylgtvcommand 192.168.1.78 info_button`
It creates at least `python`, `cmdhost`, `aiopylgtvcommand ` processes. So yesterday I pushed the button 20 times, it ended  up creating  20*3 processes :)
You can try it out yourself.

**Comment by nicko88** [comment]
>Yes, of course :) Here's the command one more time: aiopylgtvcommand 192.168.1.78 info_button
It creates at least python, cmdhost, aiopylgtvcommand processes. So yesterday I pushed the button 20 times, it ended up creating 20*3 processes :)
You can try it out yourself.

But can I even run this successfully without a responding LG TV?

What is the behavior for you if you change the IP to something that isn't a real device for example?  If you still see the problem then, I can replicate that and find a way to stop it guess, but I have still never seen that with any of the .bat files i trigger through my program.

>Or, what about this? Comma separated list in Param:
"Param": "mpc-hc64,mpc-be64,mpc-hc,mpc-be"
You loop through these values and always send a key to the first you found.

Yeah I think a list of processes makes the most sense and will work the best.

>Maybe these help. (I implemented the accepted answer in my JS remote, but - although it worked - it was so slow that I removed it, so it can also only send keys to foreground apps.) Maybe the 2nd answer?

I can use PostMessage to send the keys to a background process, but I have to consider how I will handle it compared to foreground and how I will parse out the input keys which you want to send, since it is much more complicated than SendKeys where you just send it a string representing the keys.

With PostMessage it only supports a smaller list of possible keys and it looks like I have to handle keydown and keyup manually myself.

I will most likely add a new device called backgroundkeys since the implementation and cmd/param inputs will be very different for this method.

**Comment by chros73** [comment]
OK, cheers, I'll check your first question later.

How can I specify "ctrl+alt+shift+K" keystroke? ("ctrl+K" is: `ctrl(K)`)

**Comment by nicko88** [comment]
> OK, cheers, I'll check your first question later.
> 
> How can I specify "ctrl+alt+shift+K" keystroke? ("ctrl+K" is: `ctrl(K)`)

I think ctrl(alt(shift(K))) should work.

**Comment by chros73** [comment]
> I think ctrl(alt(shift(K))) should work.

Thanks, it works! (maybe it's worth adding into [the doc](https://raw.githack.com/nicko88/HTPCRemote/master/HTPCRemote/Util/html/doc.html#keys), it's not trivial.)

One more request :) I noticed we can use hex values for the overall background color. But this doesn't work for buttons: `"Color": "#DC6E00"`
Can you also add this? Thanks!

**Comment by nicko88** [comment]
Yeah, I did not do button text color.

But if I do button text color, then someone will surely ask about custom button background color.

I *could* do custom button background color, but that would break compatibility with existing remote files, since I only allowed a few colors previously and those colors were limited to the specific Bootstrap CSS button colors.

https://getbootstrap.com/docs/4.5/components/buttons/

**Comment by nicko88** [comment]
I guess I can do it in a way that doesn't break compatibility *too* much.

I think I would default the buttons with black text and white background and people will have to go through and update all their buttons to the colors they want.

Is this all worth it? lol

**Comment by chros73** [comment]
OK, cheers.

> Does it exit when you run the .bat manually?

Guess what, now it works fine :) the cmd script exits after execution. I don't know what happened before.

Since I started to use this, I have 2 more suggestion:

1. modify how tabs work on the generated html page.
- now it reloads the page all the time when you tap on a tab
- I think it's unnecessary (user can reload it manually if it's required) and takes time on mobile
- it would be better just to switch to a tab without reloading

2. vertical spacing
- horizontal spacing of buttons are perfect this way
- but vertical is clumsy: 1 spacer is not enough, 2 is too much
- vertical spacing doesn't work with the following config (note that there's no ItemType 1 but 4! ):
```json
{
  "RemoteID": 2,
  "RemoteName": "LGTV",
  "ButtonHeight": 60,
  "RemoteBackColor": "#804000",
  "RemoteTextColor": "Gray",
  "RemoteItems": [
    {
      "ItemType": 4
    },
    {
      "ItemType": 2,
      "Label": "Info",
      "RelativeSize": 2,
      "Color": "Green",
      "Commands": [
        {
          "DeviceName": "win",
          "Cmd": "scripts/lg-info.cmd"
        }
      ]
    },
    {
      "ItemType": 3,
      "RelativeSize": 4
    }
  ]
}
```

So, what about using fixed pixels as size to specify vertical spacing? E.g. 6px height:
```json
    {
      "ItemType": 4,
      "Size": 6
    },
```

**Comment by nicko88** [comment]
You are talking about some major architectural changes which seem like they would make little difference to the operation of the application.

I barely know anything about web development and it took me forever to get the pages and tabs working how they are now lol.

I have no idea how I would make each tab not reload.  Each tab is dynamically generated html that loads on a different URL.  I don't see what benefit this would even have for all the dozens of hours of work it would take to change it.

As for vertical spacing, it was never really meant as spacing, but as a new line.  So the size depends on the size of a new line.

In your example, if you insert a second new line at the top, the content will move down, but if you are saying that's too large of gap, then I would need to also allow adding some padding value to the html somewhere for the new line element.  This I can probably find a decent way to accomplish, but there will still probably be a minimum size of whatever a new line is.

**Comment by chros73** [comment]
> You are talking about some major architectural changes ... I barely know anything about ... I write code all day at work

I know how it goes, no worries, take your time :)

> probably take awhile to work on stuff like background process hotkeys

That's fine, thanks.

> Each tab is dynamically generated html that loads on a different URL.

Oh, I see, that's why then. This is what you want:
- you only generate 1 (!) html file that includes everything! (all the tabs/buttons/etc)
  - of course now you have to be aware that all the "id"s should be different (if you use them)
- when a user tap on a tab it just hides (with css) the current tab and display the other one

Take a look at the [last section](https://stackoverflow.com/questions/6906724/is-it-possible-to-have-tabs-without-javascript/20104746#20104746) (starting from "As an alternative") of this answer, it's easier than you think, no javascript is involved just pure css.

> if you insert a second new line at the top, the content will move down

Indeed, thanks.

> I can probably find a decent way to accomplish, but there will still probably be a minimum size of whatever a new line is

That's fine :)

**Comment by chros73** [comment]
I quickly modified mine to have tabs, take a look at it: [madvr-js-remote.zip](https://github.com/nicko88/HTPCRemote/files/5282409/madvr-js-remote.zip)

Note, I haven't modified the generation part yet, tabs are hard coded.

**Comment by nicko88** [comment]
I might be able to do it as the last thing I do here.

But it brings into question how a bunch of other stuff in my program will work such as the file browser tab and youtube tab as well as the special query commands which need to pull back and display a popup message on the page dynamically.

It's a major re-architecture of how the program currently works and I just don't see the benefit really.

**Comment by chros73** [comment]
I understand, no worries, it can be v2.0 :)

**Comment by chros73** [comment]
I also [implemented](https://github.com/chros73/madvr-js-remote/blob/master/webroot/sendkeys.vbs#L19) setting mpc-* to foreground window into my app (and I refactored the rest of the code a bit). Thanks for the idea!
Probably I'll ask the mpc* devs to add new endpoint to mpc* to be able to send keys to it via web interface.

I'll probably look later at how to easily implement different colors to buttons.

**Comment by chros73** [comment]
> Probably I'll ask the mpc* devs to add new endpoint to mpc* to be able to send keys to it via web interface.

[Here it is](https://forum.doom9.org/showthread.php?p=1924538#post1924538).

**Comment by chros73** [comment]
> I'll probably look later at how to easily implement different colors to buttons.

It's also [done](https://github.com/chros73/madvr-js-remote).
The idea is:
- [create new css classes](https://github.com/chros73/madvr-js-remote/blob/master/webroot/madvr.html#L154) (normal and active) on-the-fly based on the color property of a button into the current stylesheet
- [use "data-*" attribute](https://github.com/chros73/madvr-js-remote/blob/master/webroot/madvr.html#L158) to store button specific attributes (e.g. name of active class)
- [create gradient background](https://github.com/chros73/madvr-js-remote/blob/master/webroot/madvr.html#L178) color on-the-fly based on only one color

Let me know if you need further help with understanding ...

**Comment by nicko88** [comment]
Well if I am doing custom colors I am just going to use in-line css for each button.

But you have to understand that backward compatibility is important to me.

I cannot just change the remote json format that i'm storing and break existing remotes.  I have to modify the functionality carefully so as to maintain compatibility with current remotes even though I am completely changing the way button color is asigned. (from using the built-in bootstrap classes to using custom in-line css).

**Comment by chros73** [comment]
> custom colors I am just going to use in-line css

That's also an option, I'm not sure which is easier. I've just shown you mine if it helps ...

> backward compatibility is important ... I cannot just change the remote json format

That's understandable, but I don't think you have to:
- you already have the `"Color": "Green",` attribute
- [mine](https://github.com/chros73/madvr-js-remote/blob/master/webroot/madvr-config.js#L28) is the same in this regard

Now I will take a look at the [Post/Sendmessage](https://stackoverflow.com/questions/12805345/send-combination-of-keystrokes-to-background-window) options, since the guys refused to implement it in mpc-be :)
